_target_: src.logger.CometMLWriter
project_name: "asr_deep_speech2_hw2" 
workspace: null  
run_name: "deep_speech2_baseline" 
mode: "online"  
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True  
id_length: 32 # length of the run_id
