_target_: src.logger.CometMLWriter
project_name: "istftnet_vocoder"
workspace: null
run_name: "1st try"
mode: "online"
loss_names: ["loss", "mel_loss", "adv_loss", "fm_loss", "d_loss"]
log_checkpoints: False
id_length: 32 
