defaults:
  - model: istftnet
  - writer: cometml
  - metrics: example
  - datasets: ruslan
  - dataloader: example
  - transforms: example_only_instance
  - _self_

# synthesize.py: override via CLI
checkpoint: null
input_dir: null
output_dir: null

discriminator:
  _target_: src.model.HiFiGANDiscriminator
  periods: [2, 3, 5, 7, 11]

# generator optimizer
optimizer_g:
  _target_: torch.optim.AdamW
  lr: 2e-4

# discriminator optimizer
optimizer_d:
  _target_: torch.optim.AdamW
  lr: 2e-4

lr_scheduler_g: null
lr_scheduler_d: null

loss_function:
  _target_: src.loss.iSTFTLoss
  sample_rate: 22050
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  n_mels: 80
  f_min: 0.0
  f_max: 11025
  mel_loss_weight: 45.0
  adv_loss_weight: 1.0
  fm_loss_weight: 2.0

trainer:
  log_step: 50
  n_epochs: 500
  epoch_len: null
  device_tensors: ["mel_spec", "audio"]
  resume_from: null
  device: auto
  override: false
  monitor: "min test_loss"
  save_period: 10
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
  max_grad_norm: 1.0 
  max_grad_norm_d: 1.0   # clip
